# Generated by Django 4.1.13 on 2025-03-01 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirwayBill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.IntegerField(default=0)),
                ('shipper_company_name', models.CharField(max_length=255)),
                ('shipper_contact_person', models.CharField(max_length=255)),
                ('shipper_reference', models.CharField(max_length=255)),
                ('shipper_address', models.CharField(max_length=255)),
                ('shipper_state', models.CharField(max_length=255)),
                ('shipper_city', models.CharField(max_length=255)),
                ('shipper_post_code', models.CharField(blank=True, max_length=255)),
                ('shipper_mobile_number', models.CharField(max_length=20)),
                ('shipper_phone_number', models.CharField(max_length=20)),
                ('shipper_ntn_cnic', models.CharField(max_length=255)),
                ('reciever_company_name', models.CharField(max_length=255)),
                ('reciever_contact_person', models.CharField(max_length=255)),
                ('reciever_address', models.CharField(max_length=255)),
                ('reciever_country', models.CharField(max_length=255)),
                ('reciever_state', models.CharField(max_length=255)),
                ('reciever_city', models.CharField(max_length=255)),
                ('reciever_post_code', models.CharField(blank=True, max_length=255)),
                ('reciever_mobile_number', models.CharField(max_length=20)),
                ('reciever_phone_number', models.CharField(max_length=20)),
                ('reciever_email', models.EmailField(blank=True, max_length=255)),
                ('eori_number', models.CharField(blank=True, max_length=255)),
                ('weight', models.CharField(max_length=100)),
                ('pieces', models.IntegerField()),
                ('data', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirwayBillLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('description', models.CharField(blank=True, default='In progress', max_length=400, null=True)),
                ('position', models.IntegerField(blank=True, default=1, null=True)),
                ('airway_bill_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='web_app.airwaybill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='airwaybill',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.payment'),
        ),
        migrations.AddField(
            model_name='airwaybill',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.service'),
        ),
        migrations.AddField(
            model_name='airwaybill',
            name='shipment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.shipmenttype'),
        ),
        migrations.AddField(
            model_name='airwaybill',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
